// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQdRJKUwu6_H1ZGp-8xIduhHM2bQao8o',
    appId: '1:799219235350:web:4c972376c3ba0719c25337',
    messagingSenderId: '799219235350',
    projectId: 'andonapi',
    authDomain: 'andonapi.firebaseapp.com',
    databaseURL: 'https://andonapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'andonapi.firebasestorage.app',
    measurementId: 'G-JV45T88ET7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6PClA5wiBHEhygrJlacfpQq38Nqrvgo',
    appId: '1:799219235350:android:93f1cc32d3b42e1ec25337',
    messagingSenderId: '799219235350',
    projectId: 'andonapi',
    databaseURL: 'https://andonapi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'andonapi.firebasestorage.app',
  );
}
